/**
 * Comprehensive list of major world stock exchanges with coordinates
 * and local trading hours. Used for the market hours visualization layer.
 */

export type WorldExchange = {
  id: string;
  name: string;
  shortName: string;
  city: string;
  country: string;
  coordinates: { lat: number; lng: number };
  /** Trading hours in LOCAL time (24h decimal format, e.g. 9.5 = 9:30 AM) */
  localHours: { open: number; close: number };
  timezone: string;
};

export const WORLD_EXCHANGES: WorldExchange[] = [
  {
    id: "nyse",
    name: "New York Stock Exchange",
    shortName: "NYSE",
    city: "New York",
    country: "United States",
    coordinates: { lat: 40.7069, lng: -74.0113 },
    localHours: { open: 9.5, close: 16 },
    timezone: "America/New_York",
  },
  {
    id: "nasdaq",
    name: "NASDAQ",
    shortName: "NASDAQ",
    city: "New York",
    country: "United States",
    coordinates: { lat: 40.7549, lng: -73.984 },
    localHours: { open: 9.5, close: 16 },
    timezone: "America/New_York",
  },
  {
    id: "lse",
    name: "London Stock Exchange",
    shortName: "LSE",
    city: "London",
    country: "United Kingdom",
    coordinates: { lat: 51.5155, lng: -0.0922 },
    localHours: { open: 8, close: 16.5 },
    timezone: "Europe/London",
  },
  {
    id: "tse",
    name: "Tokyo Stock Exchange",
    shortName: "TSE",
    city: "Tokyo",
    country: "Japan",
    coordinates: { lat: 35.6824, lng: 139.7741 },
    localHours: { open: 9, close: 15 },
    timezone: "Asia/Tokyo",
  },
  {
    id: "sse",
    name: "Shanghai Stock Exchange",
    shortName: "SSE",
    city: "Shanghai",
    country: "China",
    coordinates: { lat: 31.2304, lng: 121.4737 },
    localHours: { open: 9.5, close: 15 },
    timezone: "Asia/Shanghai",
  },
  {
    id: "hkex",
    name: "Hong Kong Stock Exchange",
    shortName: "HKEX",
    city: "Hong Kong",
    country: "Hong Kong",
    coordinates: { lat: 22.2783, lng: 114.1747 },
    localHours: { open: 9.5, close: 16 },
    timezone: "Asia/Hong_Kong",
  },
  {
    id: "bse",
    name: "BSE India",
    shortName: "BSE",
    city: "Mumbai",
    country: "India",
    coordinates: { lat: 18.9297, lng: 72.8332 },
    localHours: { open: 9.25, close: 15.5 },
    timezone: "Asia/Kolkata",
  },
  {
    id: "asx",
    name: "Australian Securities Exchange",
    shortName: "ASX",
    city: "Sydney",
    country: "Australia",
    coordinates: { lat: -33.8688, lng: 151.2093 },
    localHours: { open: 10, close: 16 },
    timezone: "Australia/Sydney",
  },
  {
    id: "euronext",
    name: "Euronext Paris",
    shortName: "EPA",
    city: "Paris",
    country: "France",
    coordinates: { lat: 48.8698, lng: 2.3413 },
    localHours: { open: 9, close: 17.5 },
    timezone: "Europe/Paris",
  },
  {
    id: "xetra",
    name: "XETRA (Deutsche Börse)",
    shortName: "XETRA",
    city: "Frankfurt",
    country: "Germany",
    coordinates: { lat: 50.1109, lng: 8.6821 },
    localHours: { open: 9, close: 17.5 },
    timezone: "Europe/Berlin",
  },
  {
    id: "tsx",
    name: "Toronto Stock Exchange",
    shortName: "TSX",
    city: "Toronto",
    country: "Canada",
    coordinates: { lat: 43.6479, lng: -79.3826 },
    localHours: { open: 9.5, close: 16 },
    timezone: "America/Toronto",
  },
  {
    id: "jse",
    name: "Johannesburg Stock Exchange",
    shortName: "JSE",
    city: "Johannesburg",
    country: "South Africa",
    coordinates: { lat: -26.2041, lng: 28.0473 },
    localHours: { open: 9, close: 17 },
    timezone: "Africa/Johannesburg",
  },
  {
    id: "b3",
    name: "B3 (Brasil Bolsa Balcão)",
    shortName: "B3",
    city: "São Paulo",
    country: "Brazil",
    coordinates: { lat: -23.5505, lng: -46.6333 },
    localHours: { open: 10, close: 17 },
    timezone: "America/Sao_Paulo",
  },
  {
    id: "krx",
    name: "Korea Exchange",
    shortName: "KRX",
    city: "Seoul",
    country: "South Korea",
    coordinates: { lat: 37.5665, lng: 126.978 },
    localHours: { open: 9, close: 15.5 },
    timezone: "Asia/Seoul",
  },
  {
    id: "sgx",
    name: "Singapore Exchange",
    shortName: "SGX",
    city: "Singapore",
    country: "Singapore",
    coordinates: { lat: 1.2807, lng: 103.8546 },
    localHours: { open: 9, close: 17 },
    timezone: "Asia/Singapore",
  },
  {
    id: "tadawul",
    name: "Saudi Stock Exchange",
    shortName: "TADAWUL",
    city: "Riyadh",
    country: "Saudi Arabia",
    coordinates: { lat: 24.7136, lng: 46.6753 },
    localHours: { open: 10, close: 15 },
    timezone: "Asia/Riyadh",
  },
  {
    id: "nse",
    name: "National Stock Exchange of India",
    shortName: "NSE",
    city: "Mumbai",
    country: "India",
    coordinates: { lat: 19.0558, lng: 72.8295 },
    localHours: { open: 9.25, close: 15.5 },
    timezone: "Asia/Kolkata",
  },
  {
    id: "moex",
    name: "Moscow Exchange",
    shortName: "MOEX",
    city: "Moscow",
    country: "Russia",
    coordinates: { lat: 55.7558, lng: 37.6173 },
    localHours: { open: 10, close: 18.75 },
    timezone: "Europe/Moscow",
  },
  {
    id: "nzx",
    name: "New Zealand Exchange",
    shortName: "NZX",
    city: "Wellington",
    country: "New Zealand",
    coordinates: { lat: -41.2865, lng: 174.7762 },
    localHours: { open: 10, close: 16.45 },
    timezone: "Pacific/Auckland",
  },
  {
    id: "twse",
    name: "Taiwan Stock Exchange",
    shortName: "TWSE",
    city: "Taipei",
    country: "Taiwan",
    coordinates: { lat: 25.0375, lng: 121.5637 },
    localHours: { open: 9, close: 13.5 },
    timezone: "Asia/Taipei",
  },
];
